### ISSUE TITLE
Skip [branding] and [technical]

### ISSUE THREAD

**Issue by vmavromatis** [vmavromatis/absolutely-proprietary#6]

**Comment by vmavromatis** [comment]
Fixed https://github.com/vmavromatis/absolutely-proprietary/commit/eb42ef124f45973596b5540840dff10274445a88

**Comment by coderobe** [comment]
what do you think about excluding `uses-nonfree` too, because i think it's only used when:
- some (potentially optional) dependencies are nonfree, which would already turn up in our list
- it is referring to, linking to, or endorsing problematic packages
- it integrates with problematic packages (can still be free!)

take `mesa` for example, the "issues" parabola identified are that it's recommending optional problematic software, but on its own `mesa` is licensed under MIT

**Comment by vmavromatis** [comment]
Good point! I opened a new issue https://github.com/vmavromatis/absolutely-proprietary/issues/11 so we don't mess them up!
